---
language: node_js
sudo: false
cache: yarn
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - 8

before_install:
  - yarn global add phantomjs-prebuilt
  - export PATH=$HOME/.yarn/bin:$PATH
  - phantomjs --version

install:
  - yarn

script:
  - yarn test
